### PR TITLE
fix empty gvk for VSphereCluster

### PR DESCRIPTION
**Pull request by abhinavnagaraj**

### CODE REVIEW

**Review by sadysnaat — APPROVED** [review]

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/29#" title="Author self-approved">abhinavnagaraj</a>*, *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/29#pullrequestreview-872200113" title="Approved">sadysnaat</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-vsphere-static-ip).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/OWNERS)~~ [abhinavnagaraj]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
@sadysnaat: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/29#issuecomment-1029237850):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by spectro-prow** [comment]
@abhinavnagaraj: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/29#issuecomment-1029238330):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
