### PR TITLE
Testing prow jobs

### PR DESCRIPTION
**Pull request by roshanirathi**

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#" title="Author self-approved">roshanirathi</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **abhinavnagaraj**
You can assign the PR to them by writing `/assign @abhinavnagaraj` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-vsphere-static-ip).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
Hi @roshanirathi. Thanks for your PR.

I'm waiting for a [spectrocloud](https://github.com/orgs/spectrocloud/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/spectrocloud/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-vsphere-static-ip).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#issuecomment-715197467):

>/test cluster-api-provider-vsphere-static-ip_build


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#issuecomment-715197865):

>/ok-to-test


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#issuecomment-715205362):

>/ok-to-test


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#issuecomment-715206433):

>/test cluster-api-provider-vsphere-static-ip_build


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#" title="Author self-approved">roshanirathi</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jzhoucliqr**, **zulfilee**
You can assign the PR to them by writing `/assign @jzhoucliqr @zulfilee` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-vsphere-static-ip).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/OWNERS)**
- **[prow/OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/prow/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 1f8030bf8bf2ad4118da50843324b304f8c7481b | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319594768698707968) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | a4aa2c2da9d3adb2755156ffb808be30eb107159 | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319613141444726784) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | a4aa2c2da9d3adb2755156ffb808be30eb107159 | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319625849367957504) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 2da52348b9a38766b29ee7656d3f0872380e80aa | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319636923723026432) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 2da52348b9a38766b29ee7656d3f0872380e80aa | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319640319305715712) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 2da52348b9a38766b29ee7656d3f0872380e80aa | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319642080976310272) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 2da52348b9a38766b29ee7656d3f0872380e80aa | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319645604208447488) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 2da52348b9a38766b29ee7656d3f0872380e80aa | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319648625202040832) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 8a9d17770e5c5ebe14379189a3ff1ff0837bd3a6 | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319656300379901952) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 8a9d17770e5c5ebe14379189a3ff1ff0837bd3a6 | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319661208327950336) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | d7538596298c2ac28e7c44a8fb35bc95a4f443e6 | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319668253894643712) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | cff3aa6164e52740a00ead94bf7877bbf7246c4f | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319672155369115648) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 640c8bbe0f34b720b125cc2192b5226b68fea97c | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319684486077616128) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by spectro-prow** [comment]
@roshanirathi: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
cluster-api-provider-vsphere-static-ip_image_build | 640c8bbe0f34b720b125cc2192b5226b68fea97c | [link](https://console.cloud.google.com/storage/browser/capi-prow-artifacts/pr-logs/pull/spectrocloud_cluster-api-provider-vsphere-static-ip/13/cluster-api-provider-vsphere-static-ip_image_build/1319689267655479296) | `/test cluster-api-provider-vsphere-static-ip_image_build`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by zulfilee — APPROVED** [review]

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#" title="Author self-approved">roshanirathi</a>*, *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#pullrequestreview-515928448" title="Approved">zulfilee</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jzhoucliqr**
You can assign the PR to them by writing `/assign @jzhoucliqr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-vsphere-static-ip).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/OWNERS)**
- ~~[prow/OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/prow/OWNERS)~~ [zulfilee]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#" title="Author self-approved">roshanirathi</a>*, *<a href="https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/pull/13#issuecomment-715523260" title="Approved">zulfilee</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jzhoucliqr**
You can assign the PR to them by writing `/assign @jzhoucliqr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-vsphere-static-ip).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/OWNERS)**
- ~~[prow/OWNERS](https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip/blob/master/prow/OWNERS)~~ [zulfilee]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
